{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Set up the enviroment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%capture --no-stderr\n",
    "%pip install \"pyautogen>=0.2.3\"\n",
    "%pip install -q kserve"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Imports\n",
    "import os\n",
    "import autogen"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Define your model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from kserve import KServeClient\n",
    "\n",
    "KServe = KServeClient()\n",
    "namespace = \"my-profile\"\n",
    "isvc_resp = KServe.get(\"llama2\", namespace=namespace)\n",
    "isvc_url = isvc_resp[\"status\"][\"address\"][\"url\"]\n",
    "\n",
    "print(f\"Make an API call to: {isvc_url}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Specify the model name and the endpoint\n",
    "MODEL_NAME = \"llama2\"\n",
    "LB_ENDPOINT = \"localhost:8000\"\n",
    "os.environ[\"FORCED_API_KEY\"] = \"null\"\n",
    "os.environ[\"AUTOGEN_USE_DOCKER\"] = \"0\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:The specified .env file .env does not exist.\n",
      "WARNING:root:API key not found or empty for model gpt-4. Please ensure path to .env file is correct.\n",
      "WARNING:root:API key not found or empty for model gpt-3.5-turbo. Please ensure path to .env file is correct.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[{'api_key': 'null',\n",
       "  'base_url': 'http://localhost:8000/v2',\n",
       "  'model': 'llama2'}]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# load the config list from enviroment variables\n",
    "config_list = autogen.config_list_from_dotenv(\n",
    "    dotenv_file_path='.env',\n",
    "    model_api_key_map={\n",
    "        MODEL_NAME: {\n",
    "            \"api_key_env_var\": \"FORCED_API_KEY\",\n",
    "            \"base_url\": \"http://\"+ LB_ENDPOINT + \"/v2\"\n",
    "        }\n",
    "    },\n",
    "    filter_dict={\n",
    "        \"model\": {\n",
    "           MODEL_NAME,\n",
    "        }\n",
    "    }\n",
    ")\n",
    "\n",
    "config_list"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Configure your agents\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpt_config = {\n",
    "    \"cache_seed\": 42,  # change the cache_seed for different trials\n",
    "    \"temperature\": 0, # set the forced prompt temp to 0\n",
    "    \"config_list\": config_list, # load the config from above\n",
    "    \"timeout\": 120, # set timeout to 120 seconds\n",
    "}\n",
    "\n",
    "user_proxy = autogen.UserProxyAgent(\n",
    "   name=\"Admin\",\n",
    "   system_message=\"A human admin. Interact with the planner to discuss the plan. Plan execution needs to be approved by this admin.\",\n",
    "   code_execution_config=False,\n",
    ")\n",
    "engineer = autogen.AssistantAgent(\n",
    "    name=\"Engineer\",\n",
    "    llm_config=gpt_config,\n",
    "    system_message='''Engineer. You follow an approved plan. You write python/shell code to solve tasks. Wrap the code in a code block that specifies the script type. The user can't modify your code. So do not suggest incomplete code which requires others to modify. Don't use a code block if it's not intended to be executed by the executor.\n",
    "Don't include multiple code blocks in one response. Do not ask others to copy and paste the result. Check the execution result returned by the executor.\n",
    "If the result indicates there is an error, fix the error and output the code again. Suggest the full code instead of partial code or code changes. If the error can't be fixed or if the task is not solved even after the code is executed successfully, analyze the problem, revisit your assumption, collect additional info you need, and think of a different approach to try.\n",
    "''',\n",
    ")\n",
    "scientist = autogen.AssistantAgent(\n",
    "    name=\"Scientist\",\n",
    "    llm_config=gpt_config,\n",
    "    system_message=\"\"\"Scientist. You follow an approved plan. You are able to categorize papers after seeing their abstracts printed. You don't write code.\"\"\"\n",
    ")\n",
    "planner = autogen.AssistantAgent(\n",
    "    name=\"Planner\",\n",
    "    system_message='''Planner. Suggest a plan. Revise the plan based on feedback from admin and critic, until admin approval.\n",
    "The plan may involve an engineer who can write code and a scientist who doesn't write code.\n",
    "Explain the plan first. Be clear which step is performed by an engineer, and which step is performed by a scientist.\n",
    "''',\n",
    "    llm_config=gpt_config,\n",
    ")\n",
    "executor = autogen.UserProxyAgent(\n",
    "    name=\"Executor\",\n",
    "    system_message=\"Executor. Execute the code written by the engineer and report the result.\",\n",
    "    human_input_mode=\"NEVER\",\n",
    "    code_execution_config={\"last_n_messages\": 3, \"work_dir\": \"paper\"},\n",
    ")\n",
    "critic = autogen.AssistantAgent(\n",
    "    name=\"Critic\",\n",
    "    system_message=\"Critic. Double check plan, claims, code from other agents and provide feedback. Check whether the plan includes adding verifiable info such as source URL.\",\n",
    "    llm_config=gpt_config,\n",
    ")\n",
    "\n",
    "groupchat = autogen.GroupChat(agents=[user_proxy, engineer, scientist, planner, executor, critic], messages=[], max_round=50)\n",
    "manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=gpt_config)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Begin Group Chat\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mAdmin\u001b[0m (to chat_manager):\n",
      "\n",
      "\n",
      "find papers on LLM applications from arxiv in the last week, create a markdown table of different domains.\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n"
     ]
    },
    {
     "ename": "TimeoutError",
     "evalue": "OpenAI API call timed out. This could be due to congestion or too small a timeout value. The timeout can be specified by setting the 'timeout' value (in seconds) in the llm_config (if you are using agents) or the OpenAIWrapper constructor (if you are using the OpenAIWrapper directly).",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mtimeout\u001b[0m                                   Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:10\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m      <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=8'>9</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=9'>10</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=10'>11</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:  \u001b[39m# noqa: PIE786\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sock\u001b[39m.\u001b[39;49mrecv(max_bytes)\n",
      "\u001b[0;31mtimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:67\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=65'>66</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=66'>67</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=67'>68</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:111\u001b[0m, in \u001b[0;36mResponseStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=109'>110</a>\u001b[0m \u001b[39mwith\u001b[39;00m map_httpcore_exceptions():\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=110'>111</a>\u001b[0m     \u001b[39mfor\u001b[39;00m part \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_httpcore_stream:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=111'>112</a>\u001b[0m         \u001b[39myield\u001b[39;00m part\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py:361\u001b[0m, in \u001b[0;36mConnectionPoolByteStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=359'>360</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__iter__\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Iterator[\u001b[39mbytes\u001b[39m]:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=360'>361</a>\u001b[0m     \u001b[39mfor\u001b[39;00m part \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_stream:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=361'>362</a>\u001b[0m         \u001b[39myield\u001b[39;00m part\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:337\u001b[0m, in \u001b[0;36mHTTP11ConnectionByteStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=335'>336</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mclose()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=336'>337</a>\u001b[0m \u001b[39mraise\u001b[39;00m exc\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:329\u001b[0m, in \u001b[0;36mHTTP11ConnectionByteStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=327'>328</a>\u001b[0m \u001b[39mwith\u001b[39;00m Trace(\u001b[39m\"\u001b[39m\u001b[39mreceive_response_body\u001b[39m\u001b[39m\"\u001b[39m, logger, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_request, kwargs):\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=328'>329</a>\u001b[0m     \u001b[39mfor\u001b[39;00m chunk \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_connection\u001b[39m.\u001b[39m_receive_response_body(\u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=329'>330</a>\u001b[0m         \u001b[39myield\u001b[39;00m chunk\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:198\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_response_body\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=196'>197</a>\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=197'>198</a>\u001b[0m     event \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_receive_event(timeout\u001b[39m=\u001b[39;49mtimeout)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=198'>199</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(event, h11\u001b[39m.\u001b[39mData):\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:212\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_event\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=210'>211</a>\u001b[0m \u001b[39mif\u001b[39;00m event \u001b[39mis\u001b[39;00m h11\u001b[39m.\u001b[39mNEED_DATA:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=211'>212</a>\u001b[0m     data \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_network_stream\u001b[39m.\u001b[39;49mread(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=212'>213</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mREAD_NUM_BYTES, timeout\u001b[39m=\u001b[39;49mtimeout\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=213'>214</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=215'>216</a>\u001b[0m     \u001b[39m# If we feed this case through h11 we'll raise an exception like:\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=216'>217</a>\u001b[0m     \u001b[39m#\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=217'>218</a>\u001b[0m     \u001b[39m#     httpcore.RemoteProtocolError: can't handle event type\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=221'>222</a>\u001b[0m     \u001b[39m# perspective. Instead we handle this case distinctly and treat\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=222'>223</a>\u001b[0m     \u001b[39m# it as a ConnectError.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39mrecv(max_bytes)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:14\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=12'>13</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(exc, from_exc):\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=13'>14</a>\u001b[0m         \u001b[39mraise\u001b[39;00m to_exc(exc) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=14'>15</a>\u001b[0m \u001b[39mraise\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:918\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=916'>917</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=917'>918</a>\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_client\u001b[39m.\u001b[39;49msend(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=918'>919</a>\u001b[0m         request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=919'>920</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream \u001b[39mor\u001b[39;49;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_should_stream_response_body(request\u001b[39m=\u001b[39;49mrequest),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=920'>921</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=921'>922</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=922'>923</a>\u001b[0m \u001b[39mexcept\u001b[39;00m httpx\u001b[39m.\u001b[39mTimeoutException \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:929\u001b[0m, in \u001b[0;36mClient.send\u001b[0;34m(self, request, stream, auth, follow_redirects)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=927'>928</a>\u001b[0m response\u001b[39m.\u001b[39mclose()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=928'>929</a>\u001b[0m \u001b[39mraise\u001b[39;00m exc\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:923\u001b[0m, in \u001b[0;36mClient.send\u001b[0;34m(self, request, stream, auth, follow_redirects)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=921'>922</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m stream:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=922'>923</a>\u001b[0m     response\u001b[39m.\u001b[39;49mread()\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=924'>925</a>\u001b[0m \u001b[39mreturn\u001b[39;00m response\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_models.py:811\u001b[0m, in \u001b[0;36mResponse.read\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=809'>810</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mhasattr\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39m_content\u001b[39m\u001b[39m\"\u001b[39m):\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=810'>811</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_content \u001b[39m=\u001b[39m \u001b[39mb\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39m.\u001b[39;49mjoin(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49miter_bytes())\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=811'>812</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_content\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_models.py:829\u001b[0m, in \u001b[0;36mResponse.iter_bytes\u001b[0;34m(self, chunk_size)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=827'>828</a>\u001b[0m \u001b[39mwith\u001b[39;00m request_context(request\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_request):\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=828'>829</a>\u001b[0m     \u001b[39mfor\u001b[39;00m raw_bytes \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39miter_raw():\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=829'>830</a>\u001b[0m         decoded \u001b[39m=\u001b[39m decoder\u001b[39m.\u001b[39mdecode(raw_bytes)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_models.py:887\u001b[0m, in \u001b[0;36mResponse.iter_raw\u001b[0;34m(self, chunk_size)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=885'>886</a>\u001b[0m \u001b[39mwith\u001b[39;00m request_context(request\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_request):\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=886'>887</a>\u001b[0m     \u001b[39mfor\u001b[39;00m raw_stream_bytes \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstream:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_models.py?line=887'>888</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_num_bytes_downloaded \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m \u001b[39mlen\u001b[39m(raw_stream_bytes)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:124\u001b[0m, in \u001b[0;36mBoundSyncStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=122'>123</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__iter__\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m typing\u001b[39m.\u001b[39mIterator[\u001b[39mbytes\u001b[39m]:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=123'>124</a>\u001b[0m     \u001b[39mfor\u001b[39;00m chunk \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_stream:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=124'>125</a>\u001b[0m         \u001b[39myield\u001b[39;00m chunk\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:112\u001b[0m, in \u001b[0;36mResponseStream.__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=110'>111</a>\u001b[0m \u001b[39mfor\u001b[39;00m part \u001b[39min\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_httpcore_stream:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=111'>112</a>\u001b[0m     \u001b[39myield\u001b[39;00m part\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:84\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=82'>83</a>\u001b[0m message \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(exc)\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=83'>84</a>\u001b[0m \u001b[39mraise\u001b[39;00m mapped_exc(message) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mtimeout\u001b[0m                                   Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:10\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m      <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=8'>9</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=9'>10</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=10'>11</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:  \u001b[39m# noqa: PIE786\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sock\u001b[39m.\u001b[39;49mrecv(max_bytes)\n",
      "\u001b[0;31mtimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:67\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=65'>66</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=66'>67</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=67'>68</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:231\u001b[0m, in \u001b[0;36mHTTPTransport.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=229'>230</a>\u001b[0m \u001b[39mwith\u001b[39;00m map_httpcore_exceptions():\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=230'>231</a>\u001b[0m     resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_pool\u001b[39m.\u001b[39;49mhandle_request(req)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=232'>233</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(resp\u001b[39m.\u001b[39mstream, typing\u001b[39m.\u001b[39mIterable)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py:268\u001b[0m, in \u001b[0;36mConnectionPool.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=266'>267</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mresponse_closed(status)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=267'>268</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exc\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=268'>269</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py:251\u001b[0m, in \u001b[0;36mConnectionPool.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=249'>250</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=250'>251</a>\u001b[0m     response \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39;49mhandle_request(request)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=251'>252</a>\u001b[0m \u001b[39mexcept\u001b[39;00m ConnectionNotAvailable:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=252'>253</a>\u001b[0m     \u001b[39m# The ConnectionNotAvailable exception is a special case, that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=253'>254</a>\u001b[0m     \u001b[39m# indicates we need to retry the request on a new connection.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=257'>258</a>\u001b[0m     \u001b[39m# might end up as an HTTP/2 connection, but which actually ends\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=258'>259</a>\u001b[0m     \u001b[39m# up as HTTP/1.1.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py:103\u001b[0m, in \u001b[0;36mHTTPConnection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py?line=100'>101</a>\u001b[0m         \u001b[39mraise\u001b[39;00m ConnectionNotAvailable()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py?line=102'>103</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_connection\u001b[39m.\u001b[39;49mhandle_request(request)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:133\u001b[0m, in \u001b[0;36mHTTP11Connection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=131'>132</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_response_closed()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=132'>133</a>\u001b[0m \u001b[39mraise\u001b[39;00m exc\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:111\u001b[0m, in \u001b[0;36mHTTP11Connection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=102'>103</a>\u001b[0m \u001b[39mwith\u001b[39;00m Trace(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=103'>104</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mreceive_response_headers\u001b[39m\u001b[39m\"\u001b[39m, logger, request, kwargs\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=104'>105</a>\u001b[0m ) \u001b[39mas\u001b[39;00m trace:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=105'>106</a>\u001b[0m     (\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=106'>107</a>\u001b[0m         http_version,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=107'>108</a>\u001b[0m         status,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=108'>109</a>\u001b[0m         reason_phrase,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=109'>110</a>\u001b[0m         headers,\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=110'>111</a>\u001b[0m     ) \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_receive_response_headers(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=111'>112</a>\u001b[0m     trace\u001b[39m.\u001b[39mreturn_value \u001b[39m=\u001b[39m (\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=112'>113</a>\u001b[0m         http_version,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=113'>114</a>\u001b[0m         status,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=114'>115</a>\u001b[0m         reason_phrase,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=115'>116</a>\u001b[0m         headers,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=116'>117</a>\u001b[0m     )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:176\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_response_headers\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=174'>175</a>\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=175'>176</a>\u001b[0m     event \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_receive_event(timeout\u001b[39m=\u001b[39;49mtimeout)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=176'>177</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(event, h11\u001b[39m.\u001b[39mResponse):\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:212\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_event\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=210'>211</a>\u001b[0m \u001b[39mif\u001b[39;00m event \u001b[39mis\u001b[39;00m h11\u001b[39m.\u001b[39mNEED_DATA:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=211'>212</a>\u001b[0m     data \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_network_stream\u001b[39m.\u001b[39;49mread(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=212'>213</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mREAD_NUM_BYTES, timeout\u001b[39m=\u001b[39;49mtimeout\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=213'>214</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=215'>216</a>\u001b[0m     \u001b[39m# If we feed this case through h11 we'll raise an exception like:\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=216'>217</a>\u001b[0m     \u001b[39m#\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=217'>218</a>\u001b[0m     \u001b[39m#     httpcore.RemoteProtocolError: can't handle event type\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=221'>222</a>\u001b[0m     \u001b[39m# perspective. Instead we handle this case distinctly and treat\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=222'>223</a>\u001b[0m     \u001b[39m# it as a ConnectError.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39mrecv(max_bytes)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:14\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=12'>13</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(exc, from_exc):\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=13'>14</a>\u001b[0m         \u001b[39mraise\u001b[39;00m to_exc(exc) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=14'>15</a>\u001b[0m \u001b[39mraise\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:918\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=916'>917</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=917'>918</a>\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_client\u001b[39m.\u001b[39;49msend(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=918'>919</a>\u001b[0m         request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=919'>920</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream \u001b[39mor\u001b[39;49;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_should_stream_response_body(request\u001b[39m=\u001b[39;49mrequest),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=920'>921</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=921'>922</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=922'>923</a>\u001b[0m \u001b[39mexcept\u001b[39;00m httpx\u001b[39m.\u001b[39mTimeoutException \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:915\u001b[0m, in \u001b[0;36mClient.send\u001b[0;34m(self, request, stream, auth, follow_redirects)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=912'>913</a>\u001b[0m auth \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_build_request_auth(request, auth)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=914'>915</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_handling_auth(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=915'>916</a>\u001b[0m     request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=916'>917</a>\u001b[0m     auth\u001b[39m=\u001b[39;49mauth,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=917'>918</a>\u001b[0m     follow_redirects\u001b[39m=\u001b[39;49mfollow_redirects,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=918'>919</a>\u001b[0m     history\u001b[39m=\u001b[39;49m[],\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=919'>920</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=920'>921</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:943\u001b[0m, in \u001b[0;36mClient._send_handling_auth\u001b[0;34m(self, request, auth, follow_redirects, history)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=941'>942</a>\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=942'>943</a>\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_handling_redirects(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=943'>944</a>\u001b[0m         request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=944'>945</a>\u001b[0m         follow_redirects\u001b[39m=\u001b[39;49mfollow_redirects,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=945'>946</a>\u001b[0m         history\u001b[39m=\u001b[39;49mhistory,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=946'>947</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=947'>948</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:980\u001b[0m, in \u001b[0;36mClient._send_handling_redirects\u001b[0;34m(self, request, follow_redirects, history)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=977'>978</a>\u001b[0m     hook(request)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=979'>980</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_single_request(request)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=980'>981</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:1016\u001b[0m, in \u001b[0;36mClient._send_single_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1014'>1015</a>\u001b[0m \u001b[39mwith\u001b[39;00m request_context(request\u001b[39m=\u001b[39mrequest):\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1015'>1016</a>\u001b[0m     response \u001b[39m=\u001b[39m transport\u001b[39m.\u001b[39;49mhandle_request(request)\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1017'>1018</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(response\u001b[39m.\u001b[39mstream, SyncByteStream)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:231\u001b[0m, in \u001b[0;36mHTTPTransport.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=229'>230</a>\u001b[0m \u001b[39mwith\u001b[39;00m map_httpcore_exceptions():\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=230'>231</a>\u001b[0m     resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_pool\u001b[39m.\u001b[39mhandle_request(req)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=232'>233</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(resp\u001b[39m.\u001b[39mstream, typing\u001b[39m.\u001b[39mIterable)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:84\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=82'>83</a>\u001b[0m message \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(exc)\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=83'>84</a>\u001b[0m \u001b[39mraise\u001b[39;00m mapped_exc(message) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mtimeout\u001b[0m                                   Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:10\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m      <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=8'>9</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=9'>10</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=10'>11</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:  \u001b[39m# noqa: PIE786\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sock\u001b[39m.\u001b[39;49mrecv(max_bytes)\n",
      "\u001b[0;31mtimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:67\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=65'>66</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=66'>67</a>\u001b[0m     \u001b[39myield\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=67'>68</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:231\u001b[0m, in \u001b[0;36mHTTPTransport.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=229'>230</a>\u001b[0m \u001b[39mwith\u001b[39;00m map_httpcore_exceptions():\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=230'>231</a>\u001b[0m     resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_pool\u001b[39m.\u001b[39;49mhandle_request(req)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=232'>233</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(resp\u001b[39m.\u001b[39mstream, typing\u001b[39m.\u001b[39mIterable)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py:268\u001b[0m, in \u001b[0;36mConnectionPool.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=266'>267</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mresponse_closed(status)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=267'>268</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exc\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=268'>269</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py:251\u001b[0m, in \u001b[0;36mConnectionPool.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=249'>250</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=250'>251</a>\u001b[0m     response \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39;49mhandle_request(request)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=251'>252</a>\u001b[0m \u001b[39mexcept\u001b[39;00m ConnectionNotAvailable:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=252'>253</a>\u001b[0m     \u001b[39m# The ConnectionNotAvailable exception is a special case, that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=253'>254</a>\u001b[0m     \u001b[39m# indicates we need to retry the request on a new connection.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=257'>258</a>\u001b[0m     \u001b[39m# might end up as an HTTP/2 connection, but which actually ends\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py?line=258'>259</a>\u001b[0m     \u001b[39m# up as HTTP/1.1.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py:103\u001b[0m, in \u001b[0;36mHTTPConnection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py?line=100'>101</a>\u001b[0m         \u001b[39mraise\u001b[39;00m ConnectionNotAvailable()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/connection.py?line=102'>103</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_connection\u001b[39m.\u001b[39;49mhandle_request(request)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:133\u001b[0m, in \u001b[0;36mHTTP11Connection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=131'>132</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_response_closed()\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=132'>133</a>\u001b[0m \u001b[39mraise\u001b[39;00m exc\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:111\u001b[0m, in \u001b[0;36mHTTP11Connection.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=102'>103</a>\u001b[0m \u001b[39mwith\u001b[39;00m Trace(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=103'>104</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mreceive_response_headers\u001b[39m\u001b[39m\"\u001b[39m, logger, request, kwargs\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=104'>105</a>\u001b[0m ) \u001b[39mas\u001b[39;00m trace:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=105'>106</a>\u001b[0m     (\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=106'>107</a>\u001b[0m         http_version,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=107'>108</a>\u001b[0m         status,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=108'>109</a>\u001b[0m         reason_phrase,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=109'>110</a>\u001b[0m         headers,\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=110'>111</a>\u001b[0m     ) \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_receive_response_headers(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=111'>112</a>\u001b[0m     trace\u001b[39m.\u001b[39mreturn_value \u001b[39m=\u001b[39m (\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=112'>113</a>\u001b[0m         http_version,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=113'>114</a>\u001b[0m         status,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=114'>115</a>\u001b[0m         reason_phrase,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=115'>116</a>\u001b[0m         headers,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=116'>117</a>\u001b[0m     )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:176\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_response_headers\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=174'>175</a>\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=175'>176</a>\u001b[0m     event \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_receive_event(timeout\u001b[39m=\u001b[39;49mtimeout)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=176'>177</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(event, h11\u001b[39m.\u001b[39mResponse):\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py:212\u001b[0m, in \u001b[0;36mHTTP11Connection._receive_event\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=210'>211</a>\u001b[0m \u001b[39mif\u001b[39;00m event \u001b[39mis\u001b[39;00m h11\u001b[39m.\u001b[39mNEED_DATA:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=211'>212</a>\u001b[0m     data \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_network_stream\u001b[39m.\u001b[39;49mread(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=212'>213</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mREAD_NUM_BYTES, timeout\u001b[39m=\u001b[39;49mtimeout\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=213'>214</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=215'>216</a>\u001b[0m     \u001b[39m# If we feed this case through h11 we'll raise an exception like:\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=216'>217</a>\u001b[0m     \u001b[39m#\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=217'>218</a>\u001b[0m     \u001b[39m#     httpcore.RemoteProtocolError: can't handle event type\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=221'>222</a>\u001b[0m     \u001b[39m# perspective. Instead we handle this case distinctly and treat\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_sync/http11.py?line=222'>223</a>\u001b[0m     \u001b[39m# it as a ConnectError.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py:126\u001b[0m, in \u001b[0;36mSyncStream.read\u001b[0;34m(self, max_bytes, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=124'>125</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39msettimeout(timeout)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_backends/sync.py?line=125'>126</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sock\u001b[39m.\u001b[39mrecv(max_bytes)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py:14\u001b[0m, in \u001b[0;36mmap_exceptions\u001b[0;34m(map)\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=12'>13</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(exc, from_exc):\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=13'>14</a>\u001b[0m         \u001b[39mraise\u001b[39;00m to_exc(exc) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpcore/_exceptions.py?line=14'>15</a>\u001b[0m \u001b[39mraise\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mReadTimeout\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:918\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=916'>917</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=917'>918</a>\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_client\u001b[39m.\u001b[39;49msend(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=918'>919</a>\u001b[0m         request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=919'>920</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream \u001b[39mor\u001b[39;49;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_should_stream_response_body(request\u001b[39m=\u001b[39;49mrequest),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=920'>921</a>\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=921'>922</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=922'>923</a>\u001b[0m \u001b[39mexcept\u001b[39;00m httpx\u001b[39m.\u001b[39mTimeoutException \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:915\u001b[0m, in \u001b[0;36mClient.send\u001b[0;34m(self, request, stream, auth, follow_redirects)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=912'>913</a>\u001b[0m auth \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_build_request_auth(request, auth)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=914'>915</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_handling_auth(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=915'>916</a>\u001b[0m     request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=916'>917</a>\u001b[0m     auth\u001b[39m=\u001b[39;49mauth,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=917'>918</a>\u001b[0m     follow_redirects\u001b[39m=\u001b[39;49mfollow_redirects,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=918'>919</a>\u001b[0m     history\u001b[39m=\u001b[39;49m[],\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=919'>920</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=920'>921</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:943\u001b[0m, in \u001b[0;36mClient._send_handling_auth\u001b[0;34m(self, request, auth, follow_redirects, history)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=941'>942</a>\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=942'>943</a>\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_handling_redirects(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=943'>944</a>\u001b[0m         request,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=944'>945</a>\u001b[0m         follow_redirects\u001b[39m=\u001b[39;49mfollow_redirects,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=945'>946</a>\u001b[0m         history\u001b[39m=\u001b[39;49mhistory,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=946'>947</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=947'>948</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:980\u001b[0m, in \u001b[0;36mClient._send_handling_redirects\u001b[0;34m(self, request, follow_redirects, history)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=977'>978</a>\u001b[0m     hook(request)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=979'>980</a>\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_single_request(request)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=980'>981</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_client.py:1016\u001b[0m, in \u001b[0;36mClient._send_single_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1014'>1015</a>\u001b[0m \u001b[39mwith\u001b[39;00m request_context(request\u001b[39m=\u001b[39mrequest):\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1015'>1016</a>\u001b[0m     response \u001b[39m=\u001b[39m transport\u001b[39m.\u001b[39;49mhandle_request(request)\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_client.py?line=1017'>1018</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(response\u001b[39m.\u001b[39mstream, SyncByteStream)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:231\u001b[0m, in \u001b[0;36mHTTPTransport.handle_request\u001b[0;34m(self, request)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=229'>230</a>\u001b[0m \u001b[39mwith\u001b[39;00m map_httpcore_exceptions():\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=230'>231</a>\u001b[0m     resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_pool\u001b[39m.\u001b[39mhandle_request(req)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=232'>233</a>\u001b[0m \u001b[39massert\u001b[39;00m \u001b[39misinstance\u001b[39m(resp\u001b[39m.\u001b[39mstream, typing\u001b[39m.\u001b[39mIterable)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/contextlib.py:131\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, type, value, traceback)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=129'>130</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=130'>131</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen\u001b[39m.\u001b[39;49mthrow(\u001b[39mtype\u001b[39;49m, value, traceback)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=131'>132</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=132'>133</a>\u001b[0m     \u001b[39m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=133'>134</a>\u001b[0m     \u001b[39m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/contextlib.py?line=134'>135</a>\u001b[0m     \u001b[39m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py:84\u001b[0m, in \u001b[0;36mmap_httpcore_exceptions\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=82'>83</a>\u001b[0m message \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(exc)\n\u001b[0;32m---> <a href='file:///opt/conda/lib/python3.8/site-packages/httpx/_transports/default.py?line=83'>84</a>\u001b[0m \u001b[39mraise\u001b[39;00m mapped_exc(message) \u001b[39mfrom\u001b[39;00m \u001b[39mexc\u001b[39;00m\n",
      "\u001b[0;31mReadTimeout\u001b[0m: timed out",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mAPITimeoutError\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/oai/client.py:583\u001b[0m, in \u001b[0;36mOpenAIWrapper.create\u001b[0;34m(self, **config)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=581'>582</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=582'>583</a>\u001b[0m     response \u001b[39m=\u001b[39m client\u001b[39m.\u001b[39;49mcreate(params)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=583'>584</a>\u001b[0m \u001b[39mexcept\u001b[39;00m APITimeoutError \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/oai/client.py:265\u001b[0m, in \u001b[0;36mOpenAIClient.create\u001b[0;34m(self, params)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=263'>264</a>\u001b[0m     params[\u001b[39m\"\u001b[39m\u001b[39mstream\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=264'>265</a>\u001b[0m     response \u001b[39m=\u001b[39m completions\u001b[39m.\u001b[39;49mcreate(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mparams)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=266'>267</a>\u001b[0m \u001b[39mreturn\u001b[39;00m response\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_utils/_utils.py:275\u001b[0m, in \u001b[0;36mrequired_args.<locals>.inner.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_utils/_utils.py?line=273'>274</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mTypeError\u001b[39;00m(msg)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_utils/_utils.py?line=274'>275</a>\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py:663\u001b[0m, in \u001b[0;36mCompletions.create\u001b[0;34m(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=610'>611</a>\u001b[0m \u001b[39m@required_args\u001b[39m([\u001b[39m\"\u001b[39m\u001b[39mmessages\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mmodel\u001b[39m\u001b[39m\"\u001b[39m], [\u001b[39m\"\u001b[39m\u001b[39mmessages\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mmodel\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mstream\u001b[39m\u001b[39m\"\u001b[39m])\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=611'>612</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcreate\u001b[39m(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=612'>613</a>\u001b[0m     \u001b[39mself\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=660'>661</a>\u001b[0m     timeout: \u001b[39mfloat\u001b[39m \u001b[39m|\u001b[39m httpx\u001b[39m.\u001b[39mTimeout \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m \u001b[39m|\u001b[39m NotGiven \u001b[39m=\u001b[39m NOT_GIVEN,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=661'>662</a>\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m ChatCompletion \u001b[39m|\u001b[39m Stream[ChatCompletionChunk]:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=662'>663</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_post(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=663'>664</a>\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39m/chat/completions\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=664'>665</a>\u001b[0m         body\u001b[39m=\u001b[39;49mmaybe_transform(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=665'>666</a>\u001b[0m             {\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=666'>667</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mmessages\u001b[39;49m\u001b[39m\"\u001b[39;49m: messages,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=667'>668</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mmodel\u001b[39;49m\u001b[39m\"\u001b[39;49m: model,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=668'>669</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mfrequency_penalty\u001b[39;49m\u001b[39m\"\u001b[39;49m: frequency_penalty,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=669'>670</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mfunction_call\u001b[39;49m\u001b[39m\"\u001b[39;49m: function_call,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=670'>671</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mfunctions\u001b[39;49m\u001b[39m\"\u001b[39;49m: functions,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=671'>672</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mlogit_bias\u001b[39;49m\u001b[39m\"\u001b[39;49m: logit_bias,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=672'>673</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mlogprobs\u001b[39;49m\u001b[39m\"\u001b[39;49m: logprobs,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=673'>674</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mmax_tokens\u001b[39;49m\u001b[39m\"\u001b[39;49m: max_tokens,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=674'>675</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mn\u001b[39;49m\u001b[39m\"\u001b[39;49m: n,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=675'>676</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mpresence_penalty\u001b[39;49m\u001b[39m\"\u001b[39;49m: presence_penalty,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=676'>677</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mresponse_format\u001b[39;49m\u001b[39m\"\u001b[39;49m: response_format,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=677'>678</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mseed\u001b[39;49m\u001b[39m\"\u001b[39;49m: seed,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=678'>679</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mstop\u001b[39;49m\u001b[39m\"\u001b[39;49m: stop,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=679'>680</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mstream\u001b[39;49m\u001b[39m\"\u001b[39;49m: stream,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=680'>681</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mtemperature\u001b[39;49m\u001b[39m\"\u001b[39;49m: temperature,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=681'>682</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mtool_choice\u001b[39;49m\u001b[39m\"\u001b[39;49m: tool_choice,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=682'>683</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mtools\u001b[39;49m\u001b[39m\"\u001b[39;49m: tools,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=683'>684</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mtop_logprobs\u001b[39;49m\u001b[39m\"\u001b[39;49m: top_logprobs,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=684'>685</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39mtop_p\u001b[39;49m\u001b[39m\"\u001b[39;49m: top_p,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=685'>686</a>\u001b[0m                 \u001b[39m\"\u001b[39;49m\u001b[39muser\u001b[39;49m\u001b[39m\"\u001b[39;49m: user,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=686'>687</a>\u001b[0m             },\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=687'>688</a>\u001b[0m             completion_create_params\u001b[39m.\u001b[39;49mCompletionCreateParams,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=688'>689</a>\u001b[0m         ),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=689'>690</a>\u001b[0m         options\u001b[39m=\u001b[39;49mmake_request_options(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=690'>691</a>\u001b[0m             extra_headers\u001b[39m=\u001b[39;49mextra_headers, extra_query\u001b[39m=\u001b[39;49mextra_query, extra_body\u001b[39m=\u001b[39;49mextra_body, timeout\u001b[39m=\u001b[39;49mtimeout\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=691'>692</a>\u001b[0m         ),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=692'>693</a>\u001b[0m         cast_to\u001b[39m=\u001b[39;49mChatCompletion,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=693'>694</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream \u001b[39mor\u001b[39;49;00m \u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=694'>695</a>\u001b[0m         stream_cls\u001b[39m=\u001b[39;49mStream[ChatCompletionChunk],\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/resources/chat/completions.py?line=695'>696</a>\u001b[0m     )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:1200\u001b[0m, in \u001b[0;36mSyncAPIClient.post\u001b[0;34m(self, path, cast_to, body, options, files, stream, stream_cls)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1196'>1197</a>\u001b[0m opts \u001b[39m=\u001b[39m FinalRequestOptions\u001b[39m.\u001b[39mconstruct(\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1197'>1198</a>\u001b[0m     method\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mpost\u001b[39m\u001b[39m\"\u001b[39m, url\u001b[39m=\u001b[39mpath, json_data\u001b[39m=\u001b[39mbody, files\u001b[39m=\u001b[39mto_httpx_files(files), \u001b[39m*\u001b[39m\u001b[39m*\u001b[39moptions\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1198'>1199</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1199'>1200</a>\u001b[0m \u001b[39mreturn\u001b[39;00m cast(ResponseT, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrequest(cast_to, opts, stream\u001b[39m=\u001b[39;49mstream, stream_cls\u001b[39m=\u001b[39;49mstream_cls))\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:889\u001b[0m, in \u001b[0;36mSyncAPIClient.request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=879'>880</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mrequest\u001b[39m(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=880'>881</a>\u001b[0m     \u001b[39mself\u001b[39m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=881'>882</a>\u001b[0m     cast_to: Type[ResponseT],\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=886'>887</a>\u001b[0m     stream_cls: \u001b[39mtype\u001b[39m[_StreamT] \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=887'>888</a>\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m ResponseT \u001b[39m|\u001b[39m _StreamT:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=888'>889</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_request(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=889'>890</a>\u001b[0m         cast_to\u001b[39m=\u001b[39;49mcast_to,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=890'>891</a>\u001b[0m         options\u001b[39m=\u001b[39;49moptions,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=891'>892</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=892'>893</a>\u001b[0m         stream_cls\u001b[39m=\u001b[39;49mstream_cls,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=893'>894</a>\u001b[0m         remaining_retries\u001b[39m=\u001b[39;49mremaining_retries,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=894'>895</a>\u001b[0m     )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:927\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=925'>926</a>\u001b[0m \u001b[39mif\u001b[39;00m retries \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=926'>927</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_request(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=927'>928</a>\u001b[0m         options,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=928'>929</a>\u001b[0m         cast_to,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=929'>930</a>\u001b[0m         retries,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=930'>931</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=931'>932</a>\u001b[0m         stream_cls\u001b[39m=\u001b[39;49mstream_cls,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=932'>933</a>\u001b[0m         response_headers\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=933'>934</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=935'>936</a>\u001b[0m log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mRaising timeout error\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:1013\u001b[0m, in \u001b[0;36mSyncAPIClient._retry_request\u001b[0;34m(self, options, cast_to, remaining_retries, response_headers, stream, stream_cls)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1010'>1011</a>\u001b[0m time\u001b[39m.\u001b[39msleep(timeout)\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1012'>1013</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_request(\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1013'>1014</a>\u001b[0m     options\u001b[39m=\u001b[39;49moptions,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1014'>1015</a>\u001b[0m     cast_to\u001b[39m=\u001b[39;49mcast_to,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1015'>1016</a>\u001b[0m     remaining_retries\u001b[39m=\u001b[39;49mremaining,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1016'>1017</a>\u001b[0m     stream\u001b[39m=\u001b[39;49mstream,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1017'>1018</a>\u001b[0m     stream_cls\u001b[39m=\u001b[39;49mstream_cls,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1018'>1019</a>\u001b[0m )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:927\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=925'>926</a>\u001b[0m \u001b[39mif\u001b[39;00m retries \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=926'>927</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_request(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=927'>928</a>\u001b[0m         options,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=928'>929</a>\u001b[0m         cast_to,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=929'>930</a>\u001b[0m         retries,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=930'>931</a>\u001b[0m         stream\u001b[39m=\u001b[39;49mstream,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=931'>932</a>\u001b[0m         stream_cls\u001b[39m=\u001b[39;49mstream_cls,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=932'>933</a>\u001b[0m         response_headers\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=933'>934</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=935'>936</a>\u001b[0m log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mRaising timeout error\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:1013\u001b[0m, in \u001b[0;36mSyncAPIClient._retry_request\u001b[0;34m(self, options, cast_to, remaining_retries, response_headers, stream, stream_cls)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1010'>1011</a>\u001b[0m time\u001b[39m.\u001b[39msleep(timeout)\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1012'>1013</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_request(\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1013'>1014</a>\u001b[0m     options\u001b[39m=\u001b[39;49moptions,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1014'>1015</a>\u001b[0m     cast_to\u001b[39m=\u001b[39;49mcast_to,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1015'>1016</a>\u001b[0m     remaining_retries\u001b[39m=\u001b[39;49mremaining,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1016'>1017</a>\u001b[0m     stream\u001b[39m=\u001b[39;49mstream,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1017'>1018</a>\u001b[0m     stream_cls\u001b[39m=\u001b[39;49mstream_cls,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=1018'>1019</a>\u001b[0m )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/openai/_base_client.py:937\u001b[0m, in \u001b[0;36mSyncAPIClient._request\u001b[0;34m(self, cast_to, options, remaining_retries, stream, stream_cls)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=935'>936</a>\u001b[0m     log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mRaising timeout error\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=936'>937</a>\u001b[0m     \u001b[39mraise\u001b[39;00m APITimeoutError(request\u001b[39m=\u001b[39mrequest) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/openai/_base_client.py?line=937'>938</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m err:\n",
      "\u001b[0;31mAPITimeoutError\u001b[0m: Request timed out.",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mTimeoutError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43muser_proxy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minitiate_chat\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m      2\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmanager\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m      3\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmessage\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\"\"\u001b[39;49m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;124;43mfind papers on LLM applications from arxiv in the last week, create a markdown table of different domains.\u001b[39;49m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;124;43m\"\"\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m      6\u001b[0m \u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:793\u001b[0m, in \u001b[0;36mConversableAgent.initiate_chat\u001b[0;34m(self, recipient, clear_history, silent, cache, **context)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=790'>791</a>\u001b[0m     agent\u001b[39m.\u001b[39mclient_cache \u001b[39m=\u001b[39m cache\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=791'>792</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_prepare_chat(recipient, clear_history)\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=792'>793</a>\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgenerate_init_message(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mcontext), recipient, silent\u001b[39m=\u001b[39;49msilent)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=793'>794</a>\u001b[0m summary \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_summarize_chat(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=794'>795</a>\u001b[0m     context\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39msummary_method\u001b[39m\u001b[39m\"\u001b[39m),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=795'>796</a>\u001b[0m     recipient,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=796'>797</a>\u001b[0m     prompt\u001b[39m=\u001b[39mcontext\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39msummary_prompt\u001b[39m\u001b[39m\"\u001b[39m),\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=797'>798</a>\u001b[0m     cache\u001b[39m=\u001b[39mcache,\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=798'>799</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=799'>800</a>\u001b[0m \u001b[39mfor\u001b[39;00m agent \u001b[39min\u001b[39;00m [\u001b[39mself\u001b[39m, recipient]:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:504\u001b[0m, in \u001b[0;36mConversableAgent.send\u001b[0;34m(self, message, recipient, request_reply, silent)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=501'>502</a>\u001b[0m valid \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_append_oai_message(message, \u001b[39m\"\u001b[39m\u001b[39massistant\u001b[39m\u001b[39m\"\u001b[39m, recipient)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=502'>503</a>\u001b[0m \u001b[39mif\u001b[39;00m valid:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=503'>504</a>\u001b[0m     recipient\u001b[39m.\u001b[39;49mreceive(message, \u001b[39mself\u001b[39;49m, request_reply, silent)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=504'>505</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=505'>506</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=506'>507</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mMessage can\u001b[39m\u001b[39m'\u001b[39m\u001b[39mt be converted into a valid ChatCompletion message. Either content or function_call must be provided.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=507'>508</a>\u001b[0m     )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:679\u001b[0m, in \u001b[0;36mConversableAgent.receive\u001b[0;34m(self, message, sender, request_reply, silent)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=676'>677</a>\u001b[0m \u001b[39mif\u001b[39;00m request_reply \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m \u001b[39mor\u001b[39;00m request_reply \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mreply_at_receive[sender] \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=677'>678</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=678'>679</a>\u001b[0m reply \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgenerate_reply(messages\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mchat_messages[sender], sender\u001b[39m=\u001b[39;49msender)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=679'>680</a>\u001b[0m \u001b[39mif\u001b[39;00m reply \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=680'>681</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msend(reply, sender, silent\u001b[39m=\u001b[39msilent)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:1637\u001b[0m, in \u001b[0;36mConversableAgent.generate_reply\u001b[0;34m(self, messages, sender, **kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1634'>1635</a>\u001b[0m     \u001b[39mcontinue\u001b[39;00m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1635'>1636</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_match_trigger(reply_func_tuple[\u001b[39m\"\u001b[39m\u001b[39mtrigger\u001b[39m\u001b[39m\"\u001b[39m], sender):\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1636'>1637</a>\u001b[0m     final, reply \u001b[39m=\u001b[39m reply_func(\u001b[39mself\u001b[39;49m, messages\u001b[39m=\u001b[39;49mmessages, sender\u001b[39m=\u001b[39;49msender, config\u001b[39m=\u001b[39;49mreply_func_tuple[\u001b[39m\"\u001b[39;49m\u001b[39mconfig\u001b[39;49m\u001b[39m\"\u001b[39;49m])\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1637'>1638</a>\u001b[0m     \u001b[39mif\u001b[39;00m final:\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1638'>1639</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m reply\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py:524\u001b[0m, in \u001b[0;36mGroupChatManager.run_chat\u001b[0;34m(self, messages, sender, config)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=520'>521</a>\u001b[0m     \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=521'>522</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=522'>523</a>\u001b[0m     \u001b[39m# select the next speaker\u001b[39;00m\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=523'>524</a>\u001b[0m     speaker \u001b[39m=\u001b[39m groupchat\u001b[39m.\u001b[39;49mselect_speaker(speaker, \u001b[39mself\u001b[39;49m)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=524'>525</a>\u001b[0m     \u001b[39m# let the speaker speak\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=525'>526</a>\u001b[0m     reply \u001b[39m=\u001b[39m speaker\u001b[39m.\u001b[39mgenerate_reply(sender\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py:365\u001b[0m, in \u001b[0;36mGroupChat.select_speaker\u001b[0;34m(self, last_speaker, selector)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=362'>363</a>\u001b[0m \u001b[39m# auto speaker selection\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=363'>364</a>\u001b[0m selector\u001b[39m.\u001b[39mupdate_system_message(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mselect_speaker_msg(agents))\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=364'>365</a>\u001b[0m final, name \u001b[39m=\u001b[39m selector\u001b[39m.\u001b[39;49mgenerate_oai_reply(messages)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/groupchat.py?line=365'>366</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_finalize_speaker(last_speaker, final, name, agents)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:1055\u001b[0m, in \u001b[0;36mConversableAgent.generate_oai_reply\u001b[0;34m(self, messages, sender, config)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1052'>1053</a>\u001b[0m \u001b[39mif\u001b[39;00m messages \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1053'>1054</a>\u001b[0m     messages \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_oai_messages[sender]\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1054'>1055</a>\u001b[0m extracted_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_generate_oai_reply_from_client(\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1055'>1056</a>\u001b[0m     client, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_oai_system_message \u001b[39m+\u001b[39;49m messages, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mclient_cache\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1056'>1057</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1057'>1058</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mTrue\u001b[39;00m, extracted_response\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py:1074\u001b[0m, in \u001b[0;36mConversableAgent._generate_oai_reply_from_client\u001b[0;34m(self, llm_client, messages, cache)\u001b[0m\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1070'>1071</a>\u001b[0m         all_messages\u001b[39m.\u001b[39mappend(message)\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1072'>1073</a>\u001b[0m \u001b[39m# TODO: #1143 handle token limit exceeded error\u001b[39;00m\n\u001b[0;32m-> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1073'>1074</a>\u001b[0m response \u001b[39m=\u001b[39m llm_client\u001b[39m.\u001b[39;49mcreate(\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1074'>1075</a>\u001b[0m     context\u001b[39m=\u001b[39;49mmessages[\u001b[39m-\u001b[39;49m\u001b[39m1\u001b[39;49m]\u001b[39m.\u001b[39;49mpop(\u001b[39m\"\u001b[39;49m\u001b[39mcontext\u001b[39;49m\u001b[39m\"\u001b[39;49m, \u001b[39mNone\u001b[39;49;00m),\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1075'>1076</a>\u001b[0m     messages\u001b[39m=\u001b[39;49mall_messages,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1076'>1077</a>\u001b[0m     cache\u001b[39m=\u001b[39;49mcache,\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1077'>1078</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1078'>1079</a>\u001b[0m extracted_response \u001b[39m=\u001b[39m llm_client\u001b[39m.\u001b[39mextract_text_or_completion_object(response)[\u001b[39m0\u001b[39m]\n\u001b[1;32m   <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py?line=1080'>1081</a>\u001b[0m \u001b[39mif\u001b[39;00m extracted_response \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.8/site-packages/autogen/oai/client.py:587\u001b[0m, in \u001b[0;36mOpenAIWrapper.create\u001b[0;34m(self, **config)\u001b[0m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=584'>585</a>\u001b[0m     logger\u001b[39m.\u001b[39mdebug(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mconfig \u001b[39m\u001b[39m{\u001b[39;00mi\u001b[39m}\u001b[39;00m\u001b[39m timed out\u001b[39m\u001b[39m\"\u001b[39m, exc_info\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=585'>586</a>\u001b[0m     \u001b[39mif\u001b[39;00m i \u001b[39m==\u001b[39m last:\n\u001b[0;32m--> <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=586'>587</a>\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mTimeoutError\u001b[39;00m(\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=587'>588</a>\u001b[0m             \u001b[39m\"\u001b[39m\u001b[39mOpenAI API call timed out. This could be due to congestion or too small a timeout value. The timeout can be specified by setting the \u001b[39m\u001b[39m'\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m'\u001b[39m\u001b[39m value (in seconds) in the llm_config (if you are using agents) or the OpenAIWrapper constructor (if you are using the OpenAIWrapper directly).\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=588'>589</a>\u001b[0m         ) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=589'>590</a>\u001b[0m \u001b[39mexcept\u001b[39;00m APIError \u001b[39mas\u001b[39;00m err:\n\u001b[1;32m    <a href='file:///opt/conda/lib/python3.8/site-packages/autogen/oai/client.py?line=590'>591</a>\u001b[0m     error_code \u001b[39m=\u001b[39m \u001b[39mgetattr\u001b[39m(err, \u001b[39m\"\u001b[39m\u001b[39mcode\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m)\n",
      "\u001b[0;31mTimeoutError\u001b[0m: OpenAI API call timed out. This could be due to congestion or too small a timeout value. The timeout can be specified by setting the 'timeout' value (in seconds) in the llm_config (if you are using agents) or the OpenAIWrapper constructor (if you are using the OpenAIWrapper directly)."
     ]
    }
   ],
   "source": [
    "user_proxy.initiate_chat(\n",
    "    manager,\n",
    "    message=\"\"\"\n",
    "find papers on LLM applications from arxiv in the last week, create a markdown table of different domains.\n",
    "\"\"\",\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
